/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ServiceImport } from './routes/service'
import { Route as JourneyImport } from './routes/journey'
import { Route as IndexImport } from './routes/index'
import { Route as AboutImport } from './routes/about.'

// Create/Update Routes

const ServiceRoute = ServiceImport.update({
  path: '/service',
  getParentRoute: () => rootRoute,
} as any)

const JourneyRoute = JourneyImport.update({
  path: '/journey',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyImport
      parentRoute: typeof rootRoute
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  JourneyRoute,
  ServiceRoute,
  AboutRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/journey",
        "/service",
        "/about/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/journey": {
      "filePath": "journey.tsx"
    },
    "/service": {
      "filePath": "service.tsx"
    },
    "/about/": {
      "filePath": "about..tsx"
    }
  }
}
ROUTE_MANIFEST_END */
